#
# Build
#

build { core init test/fp-edf-test }

create_boot_directory

install_config {
	<config>
		<parent-provides>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> </any-service>
		</default-route>
		<start name="fp-edf-test">
			<resource name="RAM" quantum="10M"/>
		</start>
	</config>
}

#
# Boot image
#

build_boot_image { core init fp-edf-test }

append qemu_args " -nographic -smp 4"

run_genode_until {child "fp-edf-test" exited with exit value .*\n} 40
